name: RudderStack UI Test Runner (Daily)

on:
  schedule:
    # Runs at 2:00 AM UTC every day
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
      DEV_USERNAME: ${{ secrets.DEV_USERNAME }}
      DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}
      QA_BASE_URL: ${{ secrets.QA_BASE_URL }}
      QA_USERNAME: ${{ secrets.QA_USERNAME }}
      QA_PASSWORD: ${{ secrets.QA_PASSWORD }}
      PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
      PROD_USERNAME: ${{ secrets.PROD_USERNAME }}
      PROD_PASSWORD: ${{ secrets.PROD_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:dev  # or test:qa, test:prod depending on ENV
        env:
          ENV: dev   # or qa or prod based on your test environment
